export const infosPlanets = {
  sun: {
    size: '1 392 680 km',
    distanceSun: 'N/A',
    lengthYear: 'N/A',
    lengthDay: '24 days 11 hours',
    temperature: '15 Million °C',
  },
  mercury: {
    size: '4 879 km',
    distanceSun: '58 Million km',
    lengthYear: '88 days',
    lengthDay: '58 days 15 hours 30 minutes',
    temperature: '-180°C to 430°C',
  },
  venus: {
    size: '12 104 km',
    distanceSun: '108 Million km',
    lengthYear: '225 days',
    lengthDay: '116 days 18 hours',
    temperature: '475°C',
  },
  earth: {
    size: '12 742 km',
    distanceSun: '150 Million km',
    lengthYear: '365 days',
    lengthDay: '24 hours 50 minutes',
    temperature: '-88°C to 58°C',
  },
  moon: {
    size: '1 737 km',
    distanceSun: '150 Million km',
    lengthYear: '27 days / earth',
    lengthDay: '24 hours',
    temperature: '-232°C to 127°C',
  },
  mars: {
    size: '6 779 km',
    distanceSun: '228 Million km',
    lengthYear: '687 days',
    lengthDay: '1 day 37 minutes',
    temperature: '-153°C to 20°C',
  },
  jupiter: {
    size: '142 984 km',
    distanceSun: '778 Million km',
    lengthYear: '12 years',
    lengthDay: '9 hours 56 minutes',
    temperature: '-110°C',
  },
  saturn: {
    size: '116 460 km',
    distanceSun: '1.4 Billion km',
    lengthYear: '29 years',
    lengthDay: '10 hours 42 minutes',
    temperature: '-140°C',
  },
  uranus: {
    size: '50 724 km',
    distanceSun: '2.9 Billion km',
    lengthYear: '84 years',
    lengthDay: '17 hours 14 minutes',
    temperature: '-224°C',
  },
  neptune: {
    size: '49 244 km',
    distanceSun: '4.5 Billion km',
    lengthYear: '165 years',
    lengthDay: '16 hours 6 minutes',
    temperature: '-210°C',
  },
  pluto: {
    size: '1 188 km',
    distanceSun: '5.9 Billion km',
    lengthYear: '248 years',
    lengthDay: '6 days 9 hours 36 minutes',
    temperature: '-223°C',
  },
};
